// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/categories/createCategory.ts";
import * as $$$$$$$$$1 from "./actions/categories/deleteCategory.ts";
import * as $$$$$$$$$2 from "./actions/categories/updateCategory.ts";
import * as $$$$$$$$$3 from "./actions/contact/submit.ts";
import * as $$$$$$$$$4 from "./actions/filters/createFilters.ts";
import * as $$$$$$$$$5 from "./actions/filters/updateFilter.ts";
import * as $$$$$$$$$6 from "./actions/product/additionalProperties/addAdditionalProperties.ts";
import * as $$$$$$$$$7 from "./actions/product/additionalProperties/updateAdditionaProperties.ts";
import * as $$$$$$$$$8 from "./actions/product/categories/addProductCategories.ts";
import * as $$$$$$$$$9 from "./actions/product/categories/updateProductCategories.ts";
import * as $$$$$$$$$10 from "./actions/product/createProduct.ts";
import * as $$$$$$$$$11 from "./actions/product/descriptions/addProductDescriptions.ts";
import * as $$$$$$$$$12 from "./actions/product/descriptions/updateProductDescriptions.ts";
import * as $$$$$$$$$13 from "./actions/product/documents/addDocuments.ts";
import * as $$$$$$$$$14 from "./actions/product/documents/updateDocuments.ts";
import * as $$$$$$$$$15 from "./actions/product/domains/addProductAvaliability.ts";
import * as $$$$$$$$$16 from "./actions/product/domains/updateProductAvaliability.ts";
import * as $$$$$$$$$17 from "./actions/product/images/addProductImages.ts";
import * as $$$$$$$$$18 from "./actions/product/images/updateProductImages.ts";
import * as $$$$$$$$$19 from "./actions/product/measurements/updateMeasurements.ts";
import * as $$$$$$$$$20 from "./actions/product/updateProductBasicData.ts";
import * as $$$$$$$$$21 from "./actions/product/videos/addProductVideos.ts";
import * as $$$$$$$$$22 from "./actions/product/videos/updateProductVideos.ts";
import * as $$$0 from "./loaders/guides/categories.ts";
import * as $$$1 from "./loaders/guides/productDocuments.ts";
import * as $$$2 from "./loaders/guides/products.ts";
import * as $$$3 from "./loaders/guides/suggestions.ts";
import * as $$$4 from "./loaders/menu.ts";
import * as $$$5 from "./loaders/product/avaliableBrands.ts";
import * as $$$6 from "./loaders/product/avaliableCategories.ts";
import * as $$$7 from "./loaders/product/avaliableFiltersGroups.ts";
import * as $$$8 from "./loaders/product/avaliableSites.ts";
import * as $$$9 from "./loaders/product/avaliableSkus.ts";
import * as $$$10 from "./loaders/product/details/productDetails.ts";
import * as $$$11 from "./loaders/product/list/productList.ts";
import * as $$$12 from "./loaders/product/listing/productListing.ts";
import * as $$$13 from "./loaders/testShelf.ts";
import * as $$$14 from "./loaders/whereToBuy.ts";
import * as $$$$$$27 from "./sections/blog/BlogListing.tsx";
import * as $$$$$$28 from "./sections/blog/BlogListingBreadcrumb.tsx";
import * as $$$$$$31 from "./sections/blog/BlogpostBanner.tsx";
import * as $$$$$$32 from "./sections/blog/BlogpostBreadcrumb.tsx";
import * as $$$$$$33 from "./sections/blog/BlogpostComments.tsx";
import * as $$$$$$34 from "./sections/blog/BlogpostContent.tsx";
import * as $$$$$$29 from "./sections/blog/BlogSearch.tsx";
import * as $$$$$$30 from "./sections/blog/BlogShelf.tsx";
import * as $$$$$$0 from "./sections/Component.tsx";
import * as $$$$$$35 from "./sections/container/Container.tsx";
import * as $$$$$$1 from "./sections/Content/Banner.tsx";
import * as $$$$$$2 from "./sections/Content/Breadcrumb.tsx";
import * as $$$$$$3 from "./sections/Content/Cards.tsx";
import * as $$$$$$4 from "./sections/Content/CategoryCards.tsx";
import * as $$$$$$5 from "./sections/Content/HelpCards.tsx";
import * as $$$$$$6 from "./sections/Content/ImageCards.tsx";
import * as $$$$$$7 from "./sections/Content/RawText.tsx";
import * as $$$$$$8 from "./sections/Content/TextCards.tsx";
import * as $$$$$$9 from "./sections/Content/Toast.tsx";
import * as $$$$$$10 from "./sections/Footer/Footer.tsx";
import * as $$$$$$11 from "./sections/Header/Header.tsx";
import * as $$$$$$12 from "./sections/Images/BannersMatcher.tsx";
import * as $$$$$$13 from "./sections/Images/Carousel.tsx";
import * as $$$$$$14 from "./sections/Institutional/GuidesCategories.tsx";
import * as $$$$$$15 from "./sections/Institutional/GuidesDocuments.tsx";
import * as $$$$$$16 from "./sections/Institutional/GuidesProducts.tsx";
import * as $$$$$$17 from "./sections/Institutional/Policy.tsx";
import * as $$$$$$18 from "./sections/Institutional/Support.tsx";
import * as $$$$$$19 from "./sections/Institutional/WhereToBuy.tsx";
import * as $$$$$$20 from "./sections/PageView.tsx";
import * as $$$$$$21 from "./sections/Product/ProductDetails/ProductBannerMatcher.tsx";
import * as $$$$$$22 from "./sections/Product/ProductDetails/ProductBreadcrumb.tsx";
import * as $$$$$$23 from "./sections/Product/ProductDetails/ProductPage.tsx";
import * as $$$$$$24 from "./sections/Product/ProductListing/ProductListingPage.tsx";
import * as $$$$$$25 from "./sections/Product/ProductShelf/ProductShelf.tsx";
import * as $$$$$$26 from "./sections/Social/ContactForm.tsx";

const manifest = {
  "loaders": {
    "electrolux-components/loaders/guides/categories.ts": $$$0,
    "electrolux-components/loaders/guides/productDocuments.ts": $$$1,
    "electrolux-components/loaders/guides/products.ts": $$$2,
    "electrolux-components/loaders/guides/suggestions.ts": $$$3,
    "electrolux-components/loaders/menu.ts": $$$4,
    "electrolux-components/loaders/product/avaliableBrands.ts": $$$5,
    "electrolux-components/loaders/product/avaliableCategories.ts": $$$6,
    "electrolux-components/loaders/product/avaliableFiltersGroups.ts": $$$7,
    "electrolux-components/loaders/product/avaliableSites.ts": $$$8,
    "electrolux-components/loaders/product/avaliableSkus.ts": $$$9,
    "electrolux-components/loaders/product/details/productDetails.ts": $$$10,
    "electrolux-components/loaders/product/list/productList.ts": $$$11,
    "electrolux-components/loaders/product/listing/productListing.ts": $$$12,
    "electrolux-components/loaders/testShelf.ts": $$$13,
    "electrolux-components/loaders/whereToBuy.ts": $$$14,
  },
  "sections": {
    "electrolux-components/sections/blog/BlogListing.tsx": $$$$$$27,
    "electrolux-components/sections/blog/BlogListingBreadcrumb.tsx": $$$$$$28,
    "electrolux-components/sections/blog/BlogpostBanner.tsx": $$$$$$31,
    "electrolux-components/sections/blog/BlogpostBreadcrumb.tsx": $$$$$$32,
    "electrolux-components/sections/blog/BlogpostComments.tsx": $$$$$$33,
    "electrolux-components/sections/blog/BlogpostContent.tsx": $$$$$$34,
    "electrolux-components/sections/blog/BlogSearch.tsx": $$$$$$29,
    "electrolux-components/sections/blog/BlogShelf.tsx": $$$$$$30,
    "electrolux-components/sections/Component.tsx": $$$$$$0,
    "electrolux-components/sections/container/Container.tsx": $$$$$$35,
    "electrolux-components/sections/Content/Banner.tsx": $$$$$$1,
    "electrolux-components/sections/Content/Breadcrumb.tsx": $$$$$$2,
    "electrolux-components/sections/Content/Cards.tsx": $$$$$$3,
    "electrolux-components/sections/Content/CategoryCards.tsx": $$$$$$4,
    "electrolux-components/sections/Content/HelpCards.tsx": $$$$$$5,
    "electrolux-components/sections/Content/ImageCards.tsx": $$$$$$6,
    "electrolux-components/sections/Content/RawText.tsx": $$$$$$7,
    "electrolux-components/sections/Content/TextCards.tsx": $$$$$$8,
    "electrolux-components/sections/Content/Toast.tsx": $$$$$$9,
    "electrolux-components/sections/Footer/Footer.tsx": $$$$$$10,
    "electrolux-components/sections/Header/Header.tsx": $$$$$$11,
    "electrolux-components/sections/Images/BannersMatcher.tsx": $$$$$$12,
    "electrolux-components/sections/Images/Carousel.tsx": $$$$$$13,
    "electrolux-components/sections/Institutional/GuidesCategories.tsx":
      $$$$$$14,
    "electrolux-components/sections/Institutional/GuidesDocuments.tsx":
      $$$$$$15,
    "electrolux-components/sections/Institutional/GuidesProducts.tsx": $$$$$$16,
    "electrolux-components/sections/Institutional/Policy.tsx": $$$$$$17,
    "electrolux-components/sections/Institutional/Support.tsx": $$$$$$18,
    "electrolux-components/sections/Institutional/WhereToBuy.tsx": $$$$$$19,
    "electrolux-components/sections/PageView.tsx": $$$$$$20,
    "electrolux-components/sections/Product/ProductDetails/ProductBannerMatcher.tsx":
      $$$$$$21,
    "electrolux-components/sections/Product/ProductDetails/ProductBreadcrumb.tsx":
      $$$$$$22,
    "electrolux-components/sections/Product/ProductDetails/ProductPage.tsx":
      $$$$$$23,
    "electrolux-components/sections/Product/ProductListing/ProductListingPage.tsx":
      $$$$$$24,
    "electrolux-components/sections/Product/ProductShelf/ProductShelf.tsx":
      $$$$$$25,
    "electrolux-components/sections/Social/ContactForm.tsx": $$$$$$26,
  },
  "actions": {
    "electrolux-components/actions/categories/createCategory.ts": $$$$$$$$$0,
    "electrolux-components/actions/categories/deleteCategory.ts": $$$$$$$$$1,
    "electrolux-components/actions/categories/updateCategory.ts": $$$$$$$$$2,
    "electrolux-components/actions/contact/submit.ts": $$$$$$$$$3,
    "electrolux-components/actions/filters/createFilters.ts": $$$$$$$$$4,
    "electrolux-components/actions/filters/updateFilter.ts": $$$$$$$$$5,
    "electrolux-components/actions/product/additionalProperties/addAdditionalProperties.ts":
      $$$$$$$$$6,
    "electrolux-components/actions/product/additionalProperties/updateAdditionaProperties.ts":
      $$$$$$$$$7,
    "electrolux-components/actions/product/categories/addProductCategories.ts":
      $$$$$$$$$8,
    "electrolux-components/actions/product/categories/updateProductCategories.ts":
      $$$$$$$$$9,
    "electrolux-components/actions/product/createProduct.ts": $$$$$$$$$10,
    "electrolux-components/actions/product/descriptions/addProductDescriptions.ts":
      $$$$$$$$$11,
    "electrolux-components/actions/product/descriptions/updateProductDescriptions.ts":
      $$$$$$$$$12,
    "electrolux-components/actions/product/documents/addDocuments.ts":
      $$$$$$$$$13,
    "electrolux-components/actions/product/documents/updateDocuments.ts":
      $$$$$$$$$14,
    "electrolux-components/actions/product/domains/addProductAvaliability.ts":
      $$$$$$$$$15,
    "electrolux-components/actions/product/domains/updateProductAvaliability.ts":
      $$$$$$$$$16,
    "electrolux-components/actions/product/images/addProductImages.ts":
      $$$$$$$$$17,
    "electrolux-components/actions/product/images/updateProductImages.ts":
      $$$$$$$$$18,
    "electrolux-components/actions/product/measurements/updateMeasurements.ts":
      $$$$$$$$$19,
    "electrolux-components/actions/product/updateProductBasicData.ts":
      $$$$$$$$$20,
    "electrolux-components/actions/product/videos/addProductVideos.ts":
      $$$$$$$$$21,
    "electrolux-components/actions/product/videos/updateProductVideos.ts":
      $$$$$$$$$22,
  },
  "name": "electrolux-components",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
